# Generated by Django 4.2.7 on 2023-11-27 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food',
            field=models.CharField(max_length=250),
        ),
    ]
